language: node_js
cache: 
  directories:
    - node_modules
    - ~/.npm

node_js:
  - '14'

git:
  depth: 3

script:
  - yarn build

notifications:
  email:
    recipients:
      - jiovannirdev@gmail.com
    on_success: always 
    on_failure: always 

deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local-dir: dist/ #la carpeta de archivos compilada
  target-branch: gh-page
  commit-message: "Deploy del proyecto"
  on:
    branch: master 
    #si hay un cambio en main, ejecuta todo el code, compila y envia
    #hace un deploy